igor:
  image: cloud66/igor:a
  volumes:
   - .:/opt/chat-ops-common
  links:
   - redis
  environment:
   - REDIS_HOST=redis
   - REDIS_PORT=6379
  ports:
    - "8080:8080"

igor-registration:
  image: cloud66/igor-webpage:a
  volumes:
   - .:/opt/chat-ops-common
  ports:
    - "80:8080"

redis:
  image: redis:latest
