source 'https://rubygems.org'

gem 'lita', '~> 4.6.1'
gem 'lita-slack', '~> 1.7.2'
gem 'httparty'
gem 'oauth2', '>= 1.2.0'
gem 'json'
gem 'trollop'
# gem 'factory_girl'
gem 'rspec'
# gem 'faker'
gem 'capybara', '>= 2.10.1'
# gem 'guard-rspec'
gem 'launchy'
gem 'webmock'
gem 'parallel_tests'

gem 'pry-byebug'
